name: CI

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
    lint_test_build:
      name: Lint, Test and Build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 20.x

        - name: Install Dependencies
          run: |
            npm ci

        - name: Lint
          run: |
            npm run lint -- --max-warnings 0 --no-fix

        - name: Test
          run: |
            npx stryker run

        - name: Build
          run: |
            npm run build

        - name: Upload Stryker Report
          uses: actions/upload-artifact@v2
          with:
            name: mutation-report
            path: reports/mutation
          
        - name: Upload Build
          uses: actions/upload-artifact@v2
          with:
            name: build
            path: dist
